name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  create:
jobs:
  ci-ubuntu-containers:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container: ['centos:centos7']
    steps:
      - uses: actions/checkout@v2
      - name: CentOS setup
        if: matrix.container == 'centos:centos7'
        run: |
          uname -a
          yum -y install perl perl-App-cpanminus gcc bzip2 patch
      - run: perl -V
      - run: (cpanm -n ExtUtils::MakeMaker Devel::CheckLib File::Which && cpanm -n --installdeps .) || ( cat ~/.cpanm/build.log && false )
      - name: Run tests
        env:
          HARNESS_OPTIONS: j4
        run: perl Makefile.PL && make coretest
